/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001e2e",
        "on-tertiary-fixed": "#2b1700",
        "inverse-on-surface": "#eff1f5",
        "on-primary-container": "#cfeaff",
        "surface-container-high": "#e6e8ec",
        "surface-bright": "#f7f9fd",
        "inverse-surface": "#2d3134",
        surface: "#f7f9fd",
        "surface-container": "#eceef2",
        "on-background": "#181c1f",
        "on-tertiary-fixed-variant": "#663e00",
        "on-secondary-container": "#795a03",
        "on-surface-variant": "#40484e",
        "inverse-primary": "#84cfff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        outline: "#70787f",
        "tertiary-fixed-dim": "#ffb962",
        "surface-container-low": "#f1f4f8",
        error: "#ba1a1a",
        "surface-dim": "#d8dade",
        "on-secondary-fixed-variant": "#5b4300",
        "primary-fixed-dim": "#84cfff",
        "tertiary-container": "#915b06",
        "on-tertiary-container": "#ffe1c3",
        "surface-container-highest": "#e0e3e6",
        "surface-variant": "#e0e3e6",
        "on-primary-fixed-variant": "#004c6c",
        "tertiary-fixed": "#ffddb9",
        "surface-tint": "#00658e",
        primary: "#005578",
        "secondary-fixed": "#ffdf9d",
        "primary-container": "#0b6e99",
        "on-primary": "#ffffff",
        tertiary: "#714500",
        "error-container": "#ffdad6",
        background: "#f7f9fd",
        "outline-variant": "#bfc7cf",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#251a00",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#eac167",
        "secondary-container": "#ffd578",
        secondary: "#785a02",
        "on-surface": "#181c1f",
        "primary-fixed": "#c7e7ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-xl": "64px",
        "container-max": "1280px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        gutter: "24px",
        unit: "4px",
        "margin-desktop": "48px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        "card-hover": "0 20px 50px -10px rgba(0, 85, 120, 0.12)",
        bloom:
          "0 20px 40px -10px rgba(0, 0, 0, 0.04), 0 10px 20px -5px rgba(0, 0, 0, 0.02)",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        // Brand typography — display = Plus Jakarta Sans (headings), sans = Inter (body)
        display: ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-xl-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-xl": ["60px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
